const assert=require('node:assert/strict'); const Module=require('module'); const orig=Module._load; Module._load=function(req,p,m){if(req==='express'){const e=()=>({use(){},get(){}});e.static=()=>()=>{};return e;}if(req==='socket.io')return{Server:class{}};return orig(req,p,m)}; const g=require('./server.js'); g.setIO({to(){return{emit(){}}}});
function room(){return{id:'R',maxPlayers:2,players:[{id:'P0',isBot:false,name:'P0'},{id:'P1',isBot:false,name:'P1'}],state:null,rematchVotes:new Set(),rematchTimer:null,botLoopTimeout:null}}
for(let run=0;run<1000;run++){let r=room();g.initGameState(r);let hist=[]; for(let step=0;step<5000&&!r.state.isGameOver;step++){
 let s=r.state, act='';
 if(s.pendingTake){let p=s.playersInfo[s.currentThrowerIdx],h=s.hands[p.id]||[],rs=g.getTableRanks(s.table),m=h.filter(c=>rs.has(c.rank)); if(m.length&&s.table.length<s.attackLimit&&Math.random()<.65){act=`play ${p.id} ${m[0].id}`;g.handlePlayCard(r,p.id,m[0].id)}else{act=`pass ${p.id}`;g.handlePass(r,p.id)}}
 else {let d=s.playersInfo[s.defenderIdx],u=s.table.find(x=>!x.defense); if(u){let h=s.hands[d.id]||[],v=h.filter(c=>g.canBeat(u.attack,c,s.trumpSuit)); if(v.length&&Math.random()<.75){act=`def ${d.id} ${v[0].id}`;g.handlePlayCard(r,d.id,v[0].id)}else{act=`take ${d.id}`;g.handleTake(r,d.id)}} else if(!s.table.length){let a=s.playersInfo[s.attackerIdx],h=s.hands[a.id];act=`attack ${a.id} ${h[0].id}`;g.handlePlayCard(r,a.id,h[0].id)} else {let t=s.playersInfo[s.currentThrowerIdx],h=s.hands[t.id]||[],rs=g.getTableRanks(s.table),m=h.filter(c=>rs.has(c.rank)); if(m.length&&s.table.length<s.attackLimit&&Math.random()<.7){act=`throw ${t.id} ${m[0].id}`;g.handlePlayCard(r,t.id,m[0].id)}else{act=`pass ${t.id}`;g.handlePass(r,t.id)}}}
 hist.push(act); if(hist.length>30)hist.shift();
 if(!r.state.isGameOver && r.state.table.length>0 && r.state.hands.P1.length===0 && r.state.hands.P0.length>0 && r.state.deck.length===0){console.log('reached',run,step,{a:r.state.attackerIdx,d:r.state.defenderIdx,t:r.state.currentThrowerIdx,limit:r.state.attackLimit,table:r.state.table.map(x=>[x.attack.id,x.defense&&x.defense.id]),hands:[r.state.hands.P0.length,r.state.hands.P1.length]}); console.log(hist.join('\n')); console.log('calling next manually', g.handlePass(r,'P0')); console.log('after', {over:r.state.isGameOver,a:r.state.attackerIdx,d:r.state.defenderIdx,t:r.state.currentThrowerIdx,table:r.state.table.length,hands:[r.state.hands.P0.length,r.state.hands.P1.length]}); process.exit();}
 }
}
console.log('none');
